# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, default=b'empresa/empresa.png', upload_to=b'empresa')),
                ('nit', models.DecimalField(decimal_places=0, max_digits=20)),
                ('telefono', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('latitud', models.CharField(max_length=45, unique=True)),
                ('longitud', models.CharField(max_length=45, unique=True)),
                ('imagen', models.ImageField(blank=True, default=b'empresa/empresa.png', upload_to=b'empresa')),
                ('primario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=45)),
                ('recorrido', models.CharField(max_length=45)),
                ('tipo', models.CharField(choices=[(b'buseton', b'buseton'), (b'buseta', b'buseta')], max_length=45)),
                ('foto', models.ImageField(blank=True, default=b'empresa/empresa.png', upload_to=b'empresa')),
                ('empresas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Empresa')),
                ('lugares', models.ManyToManyField(blank=True, to='home.Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lugar',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TipoLugar'),
        ),
    ]
