# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-10 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161108_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
